before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/kitty
    env:
      - CGO_ENABLED=0
    goos:
      - linux
#      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildAt={{.Date}}
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}-{{ .Version }}-{{ .Os }}.{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^test:'
brews:
  - name: kitty
    repository:
      owner: ImSingee
      name: homebrew-kitty
      token: "{{ .Env.HOMEBREW_RELEASE_GITHUB_TOKEN }}"
    install: |
      bin.install "kitty"
    test: |
      system "#{bin}/foo --version"

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
